global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: 'collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['collector:8889']

  - job_name: 'dotnet'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: [ 'host.docker.internal:9464' ]
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

